### ISSUE TITLE
InternalServerError ➡️ Status: Fail/InvalidPackage ➡️ Status: Fail/RateLimited

### ISSUE THREAD

**Issue by woctezuma** [Citrinate/FreePackages#11]
On my main account, which has everything but demos (cf. the note below), I have very few packages to try to add. However, I have noticed that I get rate-limited quite fast after getting many times the `Fail/InvalidPackage` status due to `InternalServerError`.

---

> **Note**
> For the record, this is an account which had everything, but I decided to stop adding demos. So I removed them with `ASFEnhance` and then added some `FreeOnDemand` packages back, because `ASFEnhance` is bugged. 😅 
- https://github.com/chr233/ASFEnhance/issues/158

---

I don't know if something can be done about this, as I reach the rate-limit (50) very fast. Originally, there were 20 or so packages to try, plus a few which were discovered, and the rate-limit status was ideal at 0/50.

```
2023-10-17 23:35:49|dotnet-9648|INFO|Bot|OnBotInitModules() Enable Free Packages : True
2023-10-17 23:35:49|dotnet-9648|INFO|Bot|OnBotInitModules() Free Packages Per Hour : 50
2023-10-17 23:35:49|dotnet-9648|INFO|Bot|OnBotInitModules() Free Packages Filter : {"ImportStoreFilters":false,"Types":[],"Categories":[],"Tags":[],"IgnoredTypes":["Demo"],"IgnoredTags":[],"IgnoredCategories":[],"IgnoredContentDescriptors":[],"IgnoredAppIDs":[],"IgnoreFreeWeekends":false,"MinReviewScore":0}
2023-10-17 23:36:50|dotnet-9648|DEBUG|Bot|InternalRequest() InternalServerError <- POST https://store.steampowered.com/freelicense/addfreelicense/934933
2023-10-17 23:36:50|dotnet-9648|INFO|Bot|ClaimFreeSub() ID: sub/934933 | Status: Fail/InvalidPackage
2023-10-17 23:36:56|dotnet-9648|DEBUG|Bot|InternalRequest() InternalServerError <- POST https://store.steampowered.com/freelicense/addfreelicense/952287
2023-10-17 23:36:56|dotnet-9648|INFO|Bot|ClaimFreeSub() ID: sub/952287 | Status: Fail/InvalidPackage
2023-10-17 23:37:01|dotnet-9648|DEBUG|Bot|InternalRequest() InternalServerError <- POST https://store.steampowered.com/freelicense/addfreelicense/899943
2023-10-17 23:37:01|dotnet-9648|INFO|Bot|ClaimFreeSub() ID: sub/899943 | Status: Fail/InvalidPackage
2023-10-17 23:37:07|dotnet-9648|DEBUG|Bot|InternalRequest() InternalServerError <- POST https://store.steampowered.com/freelicense/addfreelicense/952341
2023-10-17 23:37:07|dotnet-9648|INFO|Bot|ClaimFreeSub() ID: sub/952341 | Status: Fail/InvalidPackage
2023-10-17 23:37:12|dotnet-9648|INFO|Bot|ClaimFreeSub() ID: sub/83573 | Status: OK/NoDetail
2023-10-17 23:37:18|dotnet-9648|INFO|Bot|ClaimFreeApp() ID: app/1668940 | Status: Invalid
2023-10-17 23:37:25|dotnet-9648|INFO|Bot|ClaimFreeApp() ID: app/2432680 | Status: OK | Items: app/2432680, sub/875470
2023-10-17 23:37:31|dotnet-9648|DEBUG|Bot|InternalRequest() InternalServerError <- POST https://store.steampowered.com/freelicense/addfreelicense/899949
2023-10-17 23:37:31|dotnet-9648|INFO|Bot|ClaimFreeSub() ID: sub/899949 | Status: Fail/InvalidPackage
2023-10-17 23:37:37|dotnet-9648|DEBUG|Bot|InternalRequest() InternalServerError <- POST https://store.steampowered.com/freelicense/addfreelicense/899946
2023-10-17 23:37:37|dotnet-9648|INFO|Bot|ClaimFreeSub() ID: sub/899946 | Status: Fail/InvalidPackage
2023-10-17 23:37:42|dotnet-9648|DEBUG|Bot|InternalRequest() InternalServerError <- POST https://store.steampowered.com/freelicense/addfreelicense/724437
2023-10-17 23:37:42|dotnet-9648|INFO|Bot|ClaimFreeSub() ID: sub/724437 | Status: Fail/InvalidPackage
2023-10-17 23:37:48|dotnet-9648|DEBUG|Bot|InternalRequest() InternalServerError <- POST https://store.steampowered.com/freelicense/addfreelicense/947765
2023-10-17 23:37:48|dotnet-9648|INFO|Bot|ClaimFreeSub() ID: sub/947765 | Status: Fail/InvalidPackage
2023-10-17 23:37:54|dotnet-9648|DEBUG|Bot|InternalRequest() InternalServerError <- POST https://store.steampowered.com/freelicense/addfreelicense/899940
2023-10-17 23:37:54|dotnet-9648|INFO|Bot|ClaimFreeSub() ID: sub/899940 | Status: Fail/InvalidPackage
2023-10-17 23:38:00|dotnet-9648|INFO|Bot|ClaimFreeApp() ID: app/835570 | Status: Invalid
2023-10-17 23:38:05|dotnet-9648|DEBUG|Bot|InternalRequest() InternalServerError <- POST https://store.steampowered.com/freelicense/addfreelicense/951816
2023-10-17 23:38:05|dotnet-9648|INFO|Bot|ClaimFreeSub() ID: sub/951816 | Status: Fail/InvalidPackage
2023-10-17 23:38:11|dotnet-9648|INFO|Bot|ClaimFreeApp() ID: app/2391240 | Status: Invalid
2023-10-17 23:38:17|dotnet-9648|DEBUG|Bot|InternalRequest() InternalServerError <- POST https://store.steampowered.com/freelicense/addfreelicense/905335
2023-10-17 23:38:17|dotnet-9648|INFO|Bot|ClaimFreeSub() ID: sub/905335 | Status: Fail/RateLimited
2023-10-17 23:38:17|dotnet-9648|INFO|Bot|ProcessQueue() Free Package rate limit exceeded
2023-10-17 23:38:17|dotnet-9648|INFO|Bot|ProcessQueue() Pausing free package activations until 00:39:17
```

When I check some of the invalid packages, I can notice that the included app is unknown (both `App Type` and `Name`).
For instance: https://steamdb.info/sub/947765/apps/

![Picture](https://i.imgur.com/aFjIxpv.png)

So I wonder i) if this is normal, ii) if this is because the software is too fast and the free packages would become valid in an hour or so, iii) if something can be done to prevent triggering the rate-limit if the app is of unknown type or unknown name.

**Comment by Citrinate** [comment]
This is just the plugin not being aggressive enough with how it filters out invalid packages.

Presumably yes, these will all become redeemable free packages eventually, but it's hard to say when.  By the looks of them, the subs are all valid and none of the properties on them would have to change for them to be redeemable.  It's just the the apps that they grant aren't released yet, and so it's the apps that can't be redeemed.

I should be able to filter these out without the risk of missing packages.  The subs may not change, but the apps will have to, and so the plugin will have a chance to rediscover them in the future.

**Comment by woctezuma** [comment]
Thank you for your reply!

For info, you may have to postpone the fix, because ASF has an issue since yesterday's maintenance:
- https://github.com/JustArchiNET/ArchiSteamFarm/issues/3029

**Comment by Citrinate** [comment]
This new version should get rid of almost all of the invalid package errors, you can test it here: [FreePackages V1.2.0.zip](https://github.com/Citrinate/FreePackages/files/13032140/FreePackages.zip)

As for the rate limiting, I'm not sure what you mean by "too fast".  You should usually get rate limited after 50 package activations whether or not they were successful.  Some errors don't seem to actually count against the rate limit, but others do.  The plugin currently doesn't take this into consideration.  The error you're showing though isn't the plugin just thinking it's rate limited, you actually did get rate limited.

I've also noticed that if you don't wait a full hour after getting a rate limit error, Steam will sometimes let you activate a few packages (less than 50) before it rate limits you again.  I would only expect something like that to happen if you were also activating packages from outside of the plugin.  If the plugin ever sees a rate limited error, it pauses for 1 hour starting from the time it got the error.

**Comment by woctezuma** [comment]
Thank you, I will try this new version of the plugin!

Regarding the rate-limit, I was under the impression that `Fail/InvalidPackage` errors lead to reaching the rate-limit in fewer than 50 tries:
- either because the plugin would retry to add the invalid packages a few times before giving up,
- or because Valve would weigh the failed activations, e.g. you can successfully activate 50 packages per hour, but if you fail 10 times, I think you get rate-limited, so that one failure would be weighted as much as 5 successes towards the rate-limit.

I suspect it is probably the latter explanation, but it is also possible that I made a mistake and activated packages with the SteamDB script, or another tool.

**Comment by Citrinate** [comment]
It is worth testing to see how certain errors effect the limit.  I'm almost certain they are treated differently, but I'm not sure of the details.

Normally when ASF gets an error it will retry 5 times, but it's not the case here, all requests are only made once.

**Comment by woctezuma** [comment]
Thank you for the precision! I close the issue for now and will reopen if I encounter again many invalid packages!

**Comment by woctezuma** [comment]
I get these warnings with the new version. I will try again tomorrow to see if the issue persists.

```
2023-10-19 01:07:45|dotnet-10424|WARN|Bot|RefreshSession() System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at ArchiSteamFarm.Steam.Bot.RefreshSession()
2023-10-19 01:07:45|dotnet-10424|INFO|Bot|Connect() Connexion...
2023-10-19 01:07:45|dotnet-10424|INFO|Bot|OnDisconnected() Déconnecté de Steam !
2023-10-19 01:07:45|dotnet-10424|WARN|Bot|RefreshSession() System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at ArchiSteamFarm.Steam.Bot.RefreshSession()
2023-10-19 01:07:45|dotnet-10424|INFO|Bot|OnConnected() Connecté à Steam !
2023-10-19 01:07:45|dotnet-10424|INFO|Bot|OnConnected() Connexion en cours...
2023-10-19 01:07:45|dotnet-10424|INFO|Bot|OnLoggedOn() XXX/yyy connecté avec succès.
2023-10-19 01:07:55|dotnet-10424|INFO|Bot|Connect() Connexion...
2023-10-19 01:07:55|dotnet-10424|INFO|Bot|OnDisconnected() Déconnecté de Steam !
2023-10-19 01:07:55|dotnet-10424|WARN|Bot|UrlGetToHtmlDocumentWithSession() Échec !
2023-10-19 01:07:55|dotnet-10424|WARN|Bot|RefreshSession() System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at ArchiSteamFarm.Steam.Bot.RefreshSession()
2023-10-19 01:07:55|dotnet-10424|WARN|Bot|UrlGetToHtmlDocumentWithSession() Échec !
2023-10-19 01:07:55|dotnet-10424|DEBUG|Bot|UrlGetToHtmlDocumentWithSession() Échec de la requête : https://steamcommunity.com/tradingcards/boostercreator?l=english
2023-10-19 01:07:55|dotnet-10424|WARN|Bot|UrlPostToJsonObjectWithSession() Échec !
2023-10-19 01:07:55|dotnet-10424|DEBUG|Bot|UrlGetToHtmlDocumentWithSession() Échec de la requête : https://steamcommunity.com/my/badges?l=english&p=1
2023-10-19 01:07:55|dotnet-10424|ERROR|Bot|.ctor() boosterPage est invalide !
2023-10-19 01:07:55|dotnet-10424|DEBUG|Bot|UrlPostToJsonObjectWithSession() Échec de la requête : https://store.steampowered.com/freelicense/addfreelicense/952993
2023-10-19 01:07:55|dotnet-10424|WARN|Bot|IsAnythingToFarm() Impossible d'obtenir des informations sur les badges, nous allons réessayer plus tard !
2023-10-19 01:07:55|dotnet-10424|INFO|Bot|IsAnythingToFarm() Vérification de la première page des badges...
2023-10-19 01:07:55|dotnet-10424|ERROR|Bot|UpdateBoosterInfos() boosterPage est invalide !
2023-10-19 01:07:55|dotnet-10424|INFO|Bot|ClaimFreeSub() ID: sub/952993 | Status: Fail/Timeout
2023-10-19 01:07:55|dotnet-10424|WARN|Bot|UrlGetToHtmlDocumentWithSession() Échec !
2023-10-19 01:07:55|dotnet-10424|ERROR|Bot|Run() Failed to update booster information
2023-10-19 01:07:55|dotnet-10424|DEBUG|Bot|UrlGetToHtmlDocumentWithSession() Échec de la requête : https://steamcommunity.com/my/badges?l=english&p=1
2023-10-19 01:07:55|dotnet-10424|WARN|Bot|IsAnythingToFarm() Impossible d'obtenir des informations sur les badges, nous allons réessayer plus tard !
[...]
2023-10-19 01:08:15|dotnet-10424|WARN|Bot|RefreshSession() System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at ArchiSteamFarm.Steam.Bot.RefreshSession()
2023-10-19 01:08:15|dotnet-10424|INFO|Bot|OnConnected() Connecté à Steam !
2023-10-19 01:08:15|dotnet-10424|INFO|Bot|OnConnected() Connexion en cours...
2023-10-19 01:08:15|dotnet-10424|WARN|Bot|UrlGetToHtmlDocumentWithSession() Échec !
2023-10-19 01:08:15|dotnet-10424|DEBUG|Bot|UrlGetToHtmlDocumentWithSession() Échec de la requête : https://steamcommunity.com/dev/apikey?l=english
2023-10-19 01:08:15|dotnet-10424|WARN|Bot|OnPersonaState() Échec dû à une erreur : IsEligibleForListing: False
2023-10-19 01:08:15|dotnet-10424|INFO|Bot|OnLoggedOn() XXX/yyy connecté avec succès.
2023-10-19 01:08:25|dotnet-10424|INFO|Bot|Connect() Connexion...
2023-10-19 01:08:25|dotnet-10424|INFO|Bot|OnDisconnected() Déconnecté de Steam !
2023-10-19 01:08:25|dotnet-10424|WARN|Bot|RefreshSession() System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at ArchiSteamFarm.Steam.Bot.RefreshSession()
2023-10-19 01:08:25|dotnet-10424|INFO|Bot|OnConnected() Connecté à Steam !
2023-10-19 01:08:25|dotnet-10424|INFO|Bot|OnConnected() Connexion en cours...
2023-10-19 01:08:25|dotnet-10424|INFO|Bot|OnLoggedOn() XXX/yyy connecté avec succès.
2023-10-19 01:08:35|dotnet-10424|INFO|Bot|Connect() Connexion...
2023-10-19 01:08:35|dotnet-10424|INFO|Bot|OnDisconnected() Déconnecté de Steam !
2023-10-19 01:08:35|dotnet-10424|WARN|Bot|RefreshSession() System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at ArchiSteamFarm.Steam.Bot.RefreshSession()
```

**Comment by Citrinate** [comment]
I think that might be a Steam or an ASF issue.

**Comment by woctezuma** [comment]
> I think that might be a Steam or an ASF issue. I saw that happen earlier, but only on 1 of my accounts. I wasn't using that version of the plugin at the time.

Yes, a new ASF issue:
- https://github.com/JustArchiNET/ArchiSteamFarm/issues/3043
