### ISSUE TITLE
MissingMethodException

### ISSUE THREAD

**Issue by Nuklon** [Citrinate/FreePackages#12]
I'm using latest ASF-win-x64.zip. What's needed for this to start?

```txt
2023-10-19 09:40:37|ArchiSteamFarm-3292|FATAL|ASF|OnUnhandledException() System.MissingMethodException: Attempted to access a missing method.
   at FreePackages.PackageQueue.ProcessQueue()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine&)
   at FreePackages.PackageQueue.ProcessQueue()
   at FreePackages.PackageQueue.<.ctor>b__9_0(Object e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
```

**Comment by woctezuma** [comment]
> **Note**
> This plugin is only tested to work with ASF-generic.  It may or may not work with other ASF variants.

Reference: https://github.com/Citrinate/FreePackages/blob/main/README.md#installation

**Comment by Citrinate** [comment]
I'll look into this then.  This does look like an issue with using a non-generic version, but I'm willing to fix those issues as they arise.

**Comment by Nuklon** [comment]
[10:35:05] INFO 00 > OnBotInitModules() Enable Free Packages : True

Seems to work fine now 🥳 Thanks @Citrinate.
