### ISSUE TITLE
Have error when use config

### ISSUE THREAD

**Issue by LordRubiS** [Citrinate/FreePackages#13]
What format config?
 "IgnoredTypes": [],

I need exclude demos. I add  "IgnoredTypes": Demo, or  "IgnoredTypes": [Demo],

And have eror:
ct, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at ArchiSteamFarm.Steam.Storage.BotConfig.Load(String filePath, String botName)
2023-10-22 16:40:58|dotnet-5292|ERROR|ASF|RegisterBot() Your bot config is invalid. Please verify content of config/main_acc.json and try again!

**Comment by Citrinate** [comment]
It should be `"IgnoredTypes": ["Demo"]`

**Comment by LordRubiS** [comment]
Thaknks. Now it Works!

**Comment by woctezuma** [comment]
Maybe edit this line: https://github.com/Citrinate/FreePackages#types
