### ISSUE TITLE
Error after updating to DotNet v8

### ISSUE THREAD

**Issue by woctezuma** [Citrinate/FreePackages#15]
```
2023-11-18 23:27:03|dotnet-5756|INFO|ASF|InitCore() ArchiSteamFarm V5.5.0.0 (generic/98d541a0-893c-4ebb-91b8-45e2b65a4245 | .NET 8.0.0; win-x64; Microsoft Windows 10.0.19045)
2023-11-18 23:27:04|dotnet-5756|INFO|ASF|InitPlugins() Chargement FreePackages V1.2.0.0... 
```
```
2023-11-18 23:27:07|dotnet-5756|ERROR|ASF|OnBotLoggedOn() System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<ArchiSteamFarm.Web.Responses.ObjectResponse`1<!!0>> ArchiSteamFarm.Steam.Integration.ArchiWebHandler.UrlGetToJsonObjectWithSession(System.Uri, System.Collections.Generic.IReadOnlyCollection`1<System.Collections.Generic.KeyValuePair`2<System.String,System.String>>, System.Uri, ERequestOptions, Boolean, Byte, Int32, Boolean)'.
   at FreePackages.WebRequest.GetUserData(Bot bot)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at FreePackages.WebRequest.GetUserData(Bot bot)
   at FreePackages.PackageHandler.FetchUserData()
   at FreePackages.PackageHandler.OnBotLoggedOn(Bot bot)
   at FreePackages.FreePackages.OnBotLoggedOn(Bot bot)
   at ArchiSteamFarm.Core.Utilities.InParallel(IEnumerable`1 tasks)
   at ArchiSteamFarm.Plugins.PluginsCore.OnBotLoggedOn(Bot bot)
```
References:
- https://github.com/JustArchiNET/ArchiSteamFarm/releases/tag/5.5.0.0
- https://github.com/Citrinate/BoosterManager/issues/7

**Comment by Citrinate** [comment]
Acknowledged, but won't be fixing this or Citrinate/BoosterManager#7 yet as ASF V5.5 is still pre-release.  I'd like to address this before the stable release, but I'm not sure when that will happen.

**Comment by Citrinate** [comment]
Just added a pre-release version for use with ASF 5.5: https://github.com/Citrinate/FreePackages/releases/tag/1.3.0
