### ISSUE TITLE
OnUnobservedTaskException() System.ArgumentException: Requested value 'media' was not found.

### ISSUE THREAD

**Issue by shinji257** [Citrinate/FreePackages#17]
Not sure what triggers this.  It looks like it is trying to check filtering but I have nothing custom defined in the bot.  I'm not even sure where the media keyword is used.

```
2023-12-05 14:31:53|ArchiSteamFarm-52604|FATAL|ASF|OnUnobservedTaskException() System.ArgumentException: Requested value 'media' was not found.
   at System.Enum.TryParseByName(RuntimeType enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, UInt64& result)
   at System.Enum.TryParseInt32Enum(RuntimeType enumType, ReadOnlySpan`1 value, Int32 minInclusive, Int32 maxInclusive,Boolean ignoreCase, Boolean throwOnFailure, TypeCode type, Int32& result)
   at System.Enum.TryParse[TEnum](ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, TEnum& result)
   at FreePackages.FilterableApp..ctor(UInt32 id, KeyValue kv)
   at FreePackages.FilterablePackage.<>c.<AddPackageContents>b__22_0(ValueTuple`2 packageContent)
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToList()
   at FreePackages.FilterablePackage.AddPackageContents(IEnumerable`1 packageContents)
   at System.Collections.Generic.List`1.ForEach(Action`1)
   at FreePackages.PackageHandler.HandleProductInfo(List`1 productInfo)
   at FreePackages.PackageHandler.GetProductInfo(HashSet`1 appIDs, HashSet`1 packageIDs, Func`2 onFetchProductInfoCallback)
   at FreePackages.PackageHandler.HandleChanges()
   at FreePackages.PackageHandler.<>c.<<OnPICSChanges>b__19_3>d.MoveNext()
   ```

Bot config:
```json
{
  "AutoSteamSaleEvent": true,
  "CustomGamePlayedWhileFarming": "Farming...",
  "CustomGamePlayedWhileIdle": "Idling...",
  "Enabled": true,
  "SkipRefundableGames": true,
  "SteamLogin": "",
  "SteamPassword": "",
  "EnableFreePackages": true
}
```

**Comment by Citrinate** [comment]
I think I see what's causing this.  This doesn't look like a config issue.  It looks like there's a certain game which has a property value that the plugin isn't expecting to see.

If it doesn't go away on it's own, maybe you can temporarily fix this by going to your ArchiSteamFarm config folder, and edit the `FreePackages.cache` file in a text editor.  Change it to something like: `{"LastChangeNumber":21412195}`

I'm currently running the plugin, but I didn't get this error, and I don't understand why I wouldn't.  Have you been using the plugin for long or have you just started using it?  What version of ArchiSteamFarm are you using?  Also are you using an [OS specific](https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Compatibility#os-specific) version of ArchiSteamFarm or the generic version?
