### ISSUE TITLE
MissingMethodException on non-generic ASF

### ISSUE THREAD

**Issue by Citrinate** [Citrinate/FreePackages#27]
After a few seconds, plugin crashes ASF on latest version (6.0.0.3) when using a non-generic version of ASF

```
2024-03-09 11:41:47|ArchiSteamFarm-592|FATAL|ASF|OnUnhandledException() System.MissingMethodException: Attempted to access a missing method.
   at FreePackages.WebRequest.GetAppDetails(Bot bot, UInt32 appID)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine&)
   at FreePackages.WebRequest.GetAppDetails(Bot bot, UInt32 appID)
   at FreePackages.PackageQueue.ClaimFreeApp(UInt32 appID)
   at FreePackages.PackageQueue.ClaimPackage(Package package)
   at FreePackages.PackageQueue.ProcessQueue()
   at FreePackages.PackageQueue.<.ctor>b__8_0(Object e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
```

_Originally posted by @SpoogLord in https://github.com/Citrinate/FreePackages/issues/25#issuecomment-1986911526_

**Comment by JustArchi** [comment]
Might be because you're trying to deserialize into `JsonObject`. You can try deserializing into `JsonElement` instead if you need dynamic access, or to a class if possible.

**Comment by JustArchi** [comment]
Looking at the above a bit more, you should be able to safely deserialize into `Dictionary<uint, AppDetails>` instead of dynamically.
