### ISSUE TITLE
not working on ASF V6.0.4.4

### ISSUE THREAD

**Issue by Gensokyo1995** [Citrinate/FreePackages#40]
do you have time to update plugin？

**Comment by Citrinate** [comment]
Can you describe what's not working?  I'm not seeing any issues with V6.0.4.4

**Comment by Gensokyo1995** [comment]
> Can you describe what's not working and provide logs? I'm not seeing any issues with V6.0.4.4

Sorry, yesterday update to V6.0.4.4，the plugin not working, but now can be used，I don't know what happened
thanks

**Comment by Citrinate** [comment]
While I don't know what the original error was here, I suspect it was something like this:

```
ERROR|ASF|OnASFInitModules() System.TypeLoadException
   at ASFEnhance.ASFEnhance.OnASFInit(IReadOnlyDictionary`2 additionalConfigProperties)
   at ArchiSteamFarm.Plugins.PluginsCore.<>c__DisplayClass16_0.<OnASFInitModules>b__0(IASF plugin)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Threading.Tasks.Task.WhenAll(IEnumerable`1)
   at ArchiSteamFarm.Core.Utilities.InParallel(IEnumerable`1 tasks)
   at ArchiSteamFarm.Plugins.PluginsCore.OnASFInitModules(IReadOnlyDictionary`2 additionalConfigProperties)
```

And then every ~15 minutes the error: 

![48781987 19999981_image](https://github.com/Citrinate/FreePackages/assets/4910798/44963f0b-2d21-4f63-9847-1c910024534c)

These errors can appear after updating to V6.0.4.4, and are caused an out-of-date version of the ASFEnhance plugin.
