### ISSUE TITLE
Plugin crashes ASF >6.0.6.1

### ISSUE THREAD

**Issue by Bluscream** [Citrinate/FreePackages#45]
this and a bunch of other plugins started crashing asf recently, i only noticed asf not running today tho so i dont know for how long this was.
```log
2024-08-10 16:05:42|ArchiSteamFarm-18|INFO|ASF|InitCore() ArchiSteamFarm V6.0.6.2 (linux-arm64/3103c96ac7b34a18923e9a190fa3d4be | .NET 8.0.7; linux-arm64; Debian GNU/Linux 12 (bookworm)) in [/app]
2024-08-10 16:05:42|ArchiSteamFarm-18|INFO|ASF|InitCore() Copyright © 2015-2024 JustArchiNET
2024-08-10 16:05:43|ArchiSteamFarm-18|INFO|ASF|InitPlugins() Initializing Plugins...
2024-08-10 16:05:44|ArchiSteamFarm-18|ERROR|ASF|InitPlugins() System.TypeLoadException: Could not load type 'System.Diagnostics.DebuggerNonUserCodeAttribute' from assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at System.ModuleHandle.ResolveType(QCallModule, Int32, IntPtr*, Int32, IntPtr*, Int32, ObjectHandleOnStack)
   at System.ModuleHandle.ResolveTypeHandle(Int32, RuntimeTypeHandle[], RuntimeTypeHandle[])
   at System.Reflection.RuntimeModule.ResolveType(Int32, Type[], Type[])
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(MetadataToken, MetadataImport& , RuntimeModule, MetadataToken, RuntimeType, Boolean, ListBuilder`1&, RuntimeType& , IRuntimeMethodInfo& , Boolean& )
   at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1&, RuntimeModule, Int32, RuntimeType, Boolean, ListBuilder`1)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule, Int32, Int32, RuntimeType)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType, RuntimeType, Boolean)
   at System.RuntimeType.GetCustomAttributes(Type, Boolean)
   at System.Attribute.GetCustomAttributes(MemberInfo, Type, Boolean)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttributes(MemberInfo, Type, Boolean)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttributes[T](MemberInfo, Boolean)
   at System.Composition.Convention.ConventionBuilder.GetCustomAttributes(Type reflectedType, MemberInfo member)
   at System.Composition.Convention.AttributedModelProviderExtensions.GetDeclaredAttribute[TAttribute](AttributedModelProvider convention, Type reflectedType, MemberInfo member)
   at System.Composition.TypedParts.Discovery.TypeInspector.InspectTypeForPart(TypeInfo type, DiscoveredPart& part)
   at System.Composition.TypedParts.TypedPartExportDescriptorProvider..ctor(IEnumerable`1 types, AttributedModelProvider attributeContext)
   at System.Composition.Hosting.ContainerConfiguration.CreateContainer()
   at ArchiSteamFarm.Plugins.PluginsCore.InitPlugins()
```

Full list of crashing plugins is on the ASF discord https://discord.com/channels/267292556709068800/536915576682053662/1271861142418886698

**Comment by Qwest8K** [comment]
Same crash. The only unofficial plugin installed is FreePackages.
```
2024-08-11 17:24:20|ArchiSteamFarm-13440|INFO|ASF|InitCore() ArchiSteamFarm V6.0.6.2 (win-x64/4de8fa26ece04923aacfaa20cb5d111a | .NET 8.0.7; win-x64; Microsoft Windows 10.0.19045) in [D:\PPROGRAMS\ASF]
2024-08-11 17:24:21|ArchiSteamFarm-13440|INFO|ASF|InitCore() Copyright © 2015-2024 JustArchiNET
2024-08-11 17:24:22|ArchiSteamFarm-13440|INFO|ASF|InitPlugins() Инициализация Plugins...
2024-08-11 17:24:22|ArchiSteamFarm-13440|ERROR|ASF|InitPlugins() System.TypeLoadException
   at System.ModuleHandle.ResolveType(QCallModule, Int32, IntPtr*, Int32, IntPtr*, Int32, ObjectHandleOnStack)
   at System.ModuleHandle.ResolveTypeHandle(Int32, RuntimeTypeHandle[], RuntimeTypeHandle[])
   at System.Reflection.RuntimeModule.ResolveType(Int32, Type[], Type[])
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(MetadataToken, MetadataImport& , RuntimeModule, MetadataToken, RuntimeType, Boolean, ListBuilder`1&, RuntimeType& , IRuntimeMethodInfo& , Boolean& )
   at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1&, RuntimeModule, Int32, RuntimeType, Boolean, ListBuilder`1)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule, Int32, Int32, RuntimeType)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType, RuntimeType, Boolean)
   at System.RuntimeType.GetCustomAttributes(Type, Boolean)
   at System.Attribute.GetCustomAttributes(MemberInfo, Type, Boolean)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttributes(MemberInfo, Type, Boolean)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttributes[T](MemberInfo, Boolean)
   at System.Composition.Convention.ConventionBuilder.GetCustomAttributes(Type reflectedType, MemberInfo member)
   at System.Composition.Convention.AttributedModelProviderExtensions.GetDeclaredAttribute[TAttribute](AttributedModelProvider convention, Type reflectedType, MemberInfo member)
   at System.Composition.TypedParts.Discovery.TypeInspector.InspectTypeForPart(TypeInfo type, DiscoveredPart& part)
   at System.Composition.TypedParts.TypedPartExportDescriptorProvider..ctor(IEnumerable`1 types, AttributedModelProvider attributeContext)
   at System.Composition.Hosting.ContainerConfiguration.CreateContainer()
   at ArchiSteamFarm.Plugins.PluginsCore.InitPlugins()
2024-08-11 17:24:32|ArchiSteamFarm-13440|ERROR|ASF|Exit() Завершено с кодом ошибки 1!
```

**Comment by Citrinate** [comment]
Even though this is a pre-release version of ASF I still appreciate the early bug report.  This issue effects all of my plugins on ASF V6.0.6.1 and later.  I understand what the issue is and I'll try to get around to fixing in the next few days.

**Comment by JustArchi** [comment]
@Citrinate if you want/need to support several different ASF releases then it's possible with the update mechanism, you'll only need to put several assets in the zip file.

See https://github.com/JustArchiNET/ArchiSteamFarm/blob/main/ArchiSteamFarm/Plugins/Interfaces/IGitHubPluginUpdates.cs#L71-L106

**Comment by Citrinate** [comment]
The new pre-release version fixes this issue: https://github.com/Citrinate/FreePackages/releases/tag/1.5.2.0

If you're using my other plugins, there's similar pre-releases for the them.  However my CS2Interface plugin only currently works with 6.0.6.1, and not 6.0.6.2 or later.
