### ISSUE TITLE
Freepackage making asf crash

### ISSUE THREAD

**Issue by enzomtpYT** [Citrinate/FreePackages#63]
Hey i don't understand why free package makes my asf crash every so often, i looked at the logs and saw this
```2024-11-02 20:46:20|ArchiSteamFarm-7288|FATAL|ASF|OnUnhandledException() System.ArgumentNullException: Value cannot be null. (Parameter 'FreePackages.GlobalCache')
   at System.ArgumentNullException.Throw(String)
   at System.ArgumentNullException.ThrowIfNull(Object , String )
   at FreePackages.ASFInfo.DoUpdate()
   at FreePackages.ASFInfo.<>c.<<-cctor>b__6_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
   ```
   
   Is there any way to fix?
   
   Thank u in advance
   -enzomtp

**Comment by Citrinate** [comment]
I'd like to see what the lines above that log snippet are.  Also what version of the plugin, and what version of ASF?

**Comment by enzomtpYT** [comment]
The logs are written in french for some reason even tho my system is in english and asf is too. Is this a problem for you?
For the plugin version i have the latest version because i updated to latest version thinking it would fix it. And for asf i currently use "ASF 6.0.8.7 - win-x64 - 7c5eb33"

**Comment by Citrinate** [comment]
> The logs are written in french for some reason even tho my system is in english and asf is too.

That's fine, I'd still like to see them.

**Comment by enzomtpYT** [comment]
Okay then ill give the full logs
And apparently there's more errors now??
```
2024-11-02 20:00:58|ArchiSteamFarm-16344|INFO|ASF|InitCore() ArchiSteamFarm V6.0.8.7 (win-x64/3df5dc72e7944474b2170f3f645d4ad6 | .NET 8.0.10; win-x64; Microsoft Windows 10.0.20348) in [C:\Users\Administrateur\Desktop\ASF-win-x64]
2024-11-02 20:00:58|ArchiSteamFarm-16344|INFO|ASF|InitCore() Copyright © 2015-2024 JustArchiNET
2024-11-02 20:00:58|ArchiSteamFarm-16344|WARN|ASF|InitCore() Vous essayez d'exécuter ASF en tant qu'administrateur (root). Cela entraîne un risque important pour la sécurité de votre machine, et comme ASF ne nécessite pas l'accès root pour son fonctionnement, nous ne prenons pas en charge ce scénario. Utilisez l'argument --ignore-unsupported-environment si vous savez vraiment ce que vous faites.
2024-11-02 20:01:03|ArchiSteamFarm-16344|ERROR|ASF|LoadAssembliesFrom() C:\Users\Administrateur\Desktop\ASF-win-x64\plugins\ASFFreeGames\NLog.dll est invalide !
2024-11-02 20:01:03|ArchiSteamFarm-16344|WARN|ASF|LoadAssembliesFrom() System.IO.FileLoadException: 0x80131621
   at System.Runtime.Loader.AssemblyLoadContext.<LoadFromPath>g____PInvoke|5_0(IntPtr, UInt16*, UInt16*, ObjectHandleOnStack)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr, String, String, ObjectHandleOnStack)
   at System.Runtime.Loader.AssemblyLoadContext.InternalLoadFromPath(String, String)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String)
   at System.Reflection.Assembly.LoadFrom(String)
   at ArchiSteamFarm.Plugins.PluginsCore.LoadAssembliesFrom(String path)
2024-11-02 20:01:03|ArchiSteamFarm-16344|ERROR|ASF|LoadAssembliesFrom() C:\Users\Administrateur\Desktop\ASF-win-x64\plugins\ASFFreeGames\SteamKit2.dll est invalide !
2024-11-02 20:01:03|ArchiSteamFarm-16344|WARN|ASF|LoadAssembliesFrom() System.IO.FileLoadException: 0x80131621
   at System.Runtime.Loader.AssemblyLoadContext.<LoadFromPath>g____PInvoke|5_0(IntPtr, UInt16*, UInt16*, ObjectHandleOnStack)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr, String, String, ObjectHandleOnStack)
   at System.Runtime.Loader.AssemblyLoadContext.InternalLoadFromPath(String, String)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String)
   at System.Reflection.Assembly.LoadFrom(String)
   at ArchiSteamFarm.Plugins.PluginsCore.LoadAssembliesFrom(String path)
2024-11-02 20:01:03|ArchiSteamFarm-16344|ERROR|ASF|LoadAssembliesFrom() C:\Users\Administrateur\Desktop\ASF-win-x64\plugins\ASFFreeGames\System.IO.Hashing.dll est invalide !
2024-11-02 20:01:03|ArchiSteamFarm-16344|WARN|ASF|LoadAssembliesFrom() System.IO.FileLoadException: 0x80131621
   at System.Runtime.Loader.AssemblyLoadContext.<LoadFromPath>g____PInvoke|5_0(IntPtr, UInt16*, UInt16*, ObjectHandleOnStack)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr, String, String, ObjectHandleOnStack)
   at System.Runtime.Loader.AssemblyLoadContext.InternalLoadFromPath(String, String)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String)
   at System.Reflection.Assembly.LoadFrom(String)
   at ArchiSteamFarm.Plugins.PluginsCore.LoadAssembliesFrom(String path)
2024-11-02 20:01:03|ArchiSteamFarm-16344|INFO|ASF|InitPlugins() Initialisation de Plugins...
2024-11-02 20:01:03|ArchiSteamFarm-16344|INFO|ASF|InitPlugins() Chargement ItemsMatcherPlugin V6.0.8.7... 
2024-11-02 20:01:03|ArchiSteamFarm-16344|INFO|ASF|InitPlugins() "ItemsMatcherPlugin" a été chargée avec succès !
2024-11-02 20:01:03|ArchiSteamFarm-16344|INFO|ASF|InitPlugins() Chargement MobileAuthenticatorPlugin V6.0.8.7... 
2024-11-02 20:01:03|ArchiSteamFarm-16344|INFO|ASF|InitPlugins() "MobileAuthenticatorPlugin" a été chargée avec succès !
2024-11-02 20:01:03|ArchiSteamFarm-16344|INFO|ASF|InitPlugins() Chargement SteamTokenDumperPlugin V6.0.8.7... 
2024-11-02 20:01:03|ArchiSteamFarm-16344|INFO|ASF|WarnAboutIncompleteTranslation() ASF tentera d’utiliser votre langue préférée fr-FR (French (France)), mais la traduction dans cette langue n’est complète qu'à 96,6 % . Peut-être pourriez-vous nous aider à améliorer la traduction d'ASF dans votre langue?
2024-11-02 20:01:03|ArchiSteamFarm-16344|INFO|ASF|InitPlugins() "SteamTokenDumperPlugin" a été chargée avec succès !
2024-11-02 20:01:03|ArchiSteamFarm-16344|INFO|ASF|InitPlugins() Chargement ASFEnhance V2.2.3.3... 
2024-11-02 20:01:03|ArchiSteamFarm-16344|INFO|ASF|InitPlugins() "ASFEnhance" a été chargée avec succès !
2024-11-02 20:01:03|ArchiSteamFarm-16344|INFO|ASF|InitPlugins() Chargement ASFFreeGamesPlugin V1.6.1.0... 
2024-11-02 20:01:03|ArchiSteamFarm-16344|INFO|ASF|OnLoaded() Loaded ASFFreeGamesPlugin
2024-11-02 20:01:03|ArchiSteamFarm-16344|INFO|ASF|InitPlugins() "ASFFreeGamesPlugin" a été chargée avec succès !
2024-11-02 20:01:03|ArchiSteamFarm-16344|INFO|ASF|InitPlugins() Chargement BoosterManager V2.10.1.1... 
2024-11-02 20:01:03|ArchiSteamFarm-16344|INFO|ASF|OnLoaded() BoosterManager ASF Plugin by Citrinate
2024-11-02 20:01:03|ArchiSteamFarm-16344|INFO|ASF|InitPlugins() "BoosterManager" a été chargée avec succès !
2024-11-02 20:01:03|ArchiSteamFarm-16344|INFO|ASF|InitPlugins() Chargement FreePackages V1.5.2.2... 
2024-11-02 20:01:03|ArchiSteamFarm-16344|INFO|ASF|OnLoaded() Free Packages ASF Plugin by Citrinate
2024-11-02 20:01:03|ArchiSteamFarm-16344|INFO|ASF|InitPlugins() "FreePackages" a été chargée avec succès !
2024-11-02 20:01:03|ArchiSteamFarm-16344|INFO|ASF|InitPlugins() Vous avez chargé un ou plusieurs plugins personnalisés dans ASF. Étant donné que nous ne pouvons pas offrir de support pour les configurations moddées, veuillez contacter les développeurs appropriés des plugins que vous avez décidé d'utiliser en cas de problème.
2024-11-02 20:01:03|ArchiSteamFarm-16344|INFO|ASF|InitPlugins() Le plugin ASFEnhance (ASFEnhance) a été désactivé à partir des mises à jour automatiques, malgré la prise en charge de cette fonctionnalité.
2024-11-02 20:01:03|ArchiSteamFarm-16344|INFO|ASF|InitPlugins() Le plugin BoosterManager (BoosterManager) a été désactivé à partir des mises à jour automatiques, malgré la prise en charge de cette fonctionnalité.
2024-11-02 20:01:03|ArchiSteamFarm-16344|INFO|ASF|InitPlugins() Le plugin FreePackages (FreePackages) a été désactivé à partir des mises à jour automatiques, malgré la prise en charge de cette fonctionnalité.
2024-11-02 20:01:03|ArchiSteamFarm-16344|INFO|ASF|UpdateAndRestart() ASF recherchera automatiquement de nouvelles mises à jour tous les 1 jour.
2024-11-02 20:01:03|ArchiSteamFarm-16344|INFO|ASF|UpdateASF() Recherche d'une nouvelle version...
2024-11-02 20:01:04|ArchiSteamFarm-16344|INFO|ASF|UpdateASF() Version locale : 6.0.8.7 | Version la plus récente : 6.0.8.7
2024-11-02 20:01:04|ArchiSteamFarm-16344|INFO|ASF|OnASFInit() 
==========================================================================
 █████╗ ███████╗███████╗███████╗███╗   ██╗██╗  ██╗ █████╗ ███╗   ██╗ ██████╗███████╗
██╔══██╗██╔════╝██╔════╝██╔════╝████╗  ██║██║  ██║██╔══██╗████╗  ██║██╔════╝██╔════╝
███████║███████╗█████╗  █████╗  ██╔██╗ ██║███████║███████║██╔██╗ ██║██║     █████╗  
██╔══██║╚════██║██╔══╝  ██╔══╝  ██║╚██╗██║██╔══██║██╔══██║██║╚██╗██║██║     ██╔══╝  
██║  ██║███████║██║     ███████╗██║ ╚████║██║  ██║██║  ██║██║ ╚████║╚██████╗███████╗
╚═╝  ╚═╝╚══════╝╚═╝     ╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═══╝ ╚═════╝╚══════╝
==========================================================================
ASFEnhance Version 2.2.3.3
Developed by Chr_, email chr@chrxw.com
Donate: https://afdian.com/@chr233
==========================================================================
Submodule not loaded
==========================================================================

2024-11-02 20:01:04|ArchiSteamFarm-16344|ERROR|ASF|CreateOrLoad() System.Text.Json.JsonException: '0x00' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: '0x00' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader&, ExceptionResource, Byte , ReadOnlySpan`1 )
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader&, JsonSerializerOptions, ReadStack&)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& , JsonReaderException)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader&, JsonSerializerOptions, ReadStack&)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.Deserialize(Utf8JsonReader&, ReadStack&)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1, JsonTypeInfo`1, Nullable`1 )
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1, JsonTypeInfo`1)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String , JsonSerializerOptions )
   at ArchiSteamFarm.Helpers.Json.JsonUtilities.ToJsonObject[T](String json)
   at FreePackages.GlobalCache.CreateOrLoad()
2024-11-02 20:01:04|ArchiSteamFarm-16344|INFO|ASF|Load() Chargement du cache STD global...
2024-11-02 20:01:04|ArchiSteamFarm-16344|INFO|ASF|Load() Validation de l'intégrité du cache STD global...
2024-11-02 20:01:04|ArchiSteamFarm-16344|INFO|ASF|OnASFInit() SteamTokenDumperPlugin has been initialized successfully, thank you in advance for your help. The first submission will happen in approximately 39 minutes.
2024-11-02 20:01:04|ArchiSteamFarm-16344|INFO|ASF|StartInteractiveConsole() La console interactive est maintenant active, tapez 'c' pour entrer en mode commande.
2024-11-02 20:01:04|ArchiSteamFarm-16344|INFO|ASF|Start() Démarrage du serveur IPC...
2024-11-02 20:01:04|ArchiSteamFarm-16344|ERROR|ASF|LoadAssembliesFrom() C:\Users\Administrateur\Desktop\ASF-win-x64\plugins\ASFFreeGames\NLog.dll est invalide !
2024-11-02 20:01:04|ArchiSteamFarm-16344|WARN|ASF|LoadAssembliesFrom() System.IO.FileLoadException: 0x80131621
   at System.Runtime.Loader.AssemblyLoadContext.<LoadFromPath>g____PInvoke|5_0(IntPtr, UInt16*, UInt16*, ObjectHandleOnStack)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr, String, String, ObjectHandleOnStack)
   at System.Runtime.Loader.AssemblyLoadContext.InternalLoadFromPath(String, String)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String)
   at System.Reflection.Assembly.LoadFrom(String)
   at ArchiSteamFarm.Plugins.PluginsCore.LoadAssembliesFrom(String path)
2024-11-02 20:01:04|ArchiSteamFarm-16344|ERROR|ASF|LoadAssembliesFrom() C:\Users\Administrateur\Desktop\ASF-win-x64\plugins\ASFFreeGames\SteamKit2.dll est invalide !
2024-11-02 20:01:04|ArchiSteamFarm-16344|WARN|ASF|LoadAssembliesFrom() System.IO.FileLoadException: 0x80131621
   at System.Runtime.Loader.AssemblyLoadContext.<LoadFromPath>g____PInvoke|5_0(IntPtr, UInt16*, UInt16*, ObjectHandleOnStack)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr, String, String, ObjectHandleOnStack)
   at System.Runtime.Loader.AssemblyLoadContext.InternalLoadFromPath(String, String)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String)
   at System.Reflection.Assembly.LoadFrom(String)
   at ArchiSteamFarm.Plugins.PluginsCore.LoadAssembliesFrom(String path)
2024-11-02 20:01:04|ArchiSteamFarm-16344|ERROR|ASF|LoadAssembliesFrom() C:\Users\Administrateur\Desktop\ASF-win-x64\plugins\ASFFreeGames\System.IO.Hashing.dll est invalide !
2024-11-02 20:01:04|ArchiSteamFarm-16344|WARN|ASF|LoadAssembliesFrom() System.IO.FileLoadException: 0x80131621
   at System.Runtime.Loader.AssemblyLoadContext.<LoadFromPath>g____PInvoke|5_0(IntPtr, UInt16*, UInt16*, ObjectHandleOnStack)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr, String, String, ObjectHandleOnStack)
   at System.Runtime.Loader.AssemblyLoadContext.InternalLoadFromPath(String, String)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String)
   at System.Reflection.Assembly.LoadFrom(String)
   at ArchiSteamFarm.Plugins.PluginsCore.LoadAssembliesFrom(String path)
2024-11-02 20:01:05|ArchiSteamFarm-16344|INFO|Microsoft.Hosting.Lifetime|Now listening on: http://0.0.0.0:1242
2024-11-02 20:01:05|ArchiSteamFarm-16344|INFO|Microsoft.Hosting.Lifetime|Now listening on: http://[::1]:1242
2024-11-02 20:01:05|ArchiSteamFarm-16344|INFO|Microsoft.Hosting.Lifetime|Application started. Press Ctrl+C to shut down.
2024-11-02 20:01:05|ArchiSteamFarm-16344|INFO|Microsoft.Hosting.Lifetime|Hosting environment: Production
2024-11-02 20:01:05|ArchiSteamFarm-16344|INFO|Microsoft.Hosting.Lifetime|Content root path: C:\Users\Administrateur\Desktop\ASF-win-x64
2024-11-02 20:01:05|ArchiSteamFarm-16344|INFO|ASF|Start() Serveur IPC prêt !
2024-11-02 20:01:05|ArchiSteamFarm-16344|INFO|enzomtp|OnBotInitModules() Enable Free Packages : True
2024-11-02 20:01:05|ArchiSteamFarm-16344|INFO|DiamaXV|Start() Démarrage...
2024-11-02 20:01:05|ArchiSteamFarm-16344|INFO|Draconix|Start() Démarrage...
2024-11-02 20:01:05|ArchiSteamFarm-16344|INFO|DiamaXV|Connect() Connexion...
2024-11-02 20:01:05|ArchiSteamFarm-16344|INFO|enzomtp|OnBotInitModules() Free Packages Filters : [{"ImportStoreFilters":false,"Types":[],"Categories":[],"Tags":[],"IgnoredTypes":["Demo","DLC","Music","Video","Tool"],"IgnoredTags":[],"IgnoredCategories":[],"IgnoredContentDescriptors":[],"IgnoredAppIDs":[],"IgnoreFreeWeekends":false,"MinReviewScore":0,"Languages":[],"PlaytestMode":0,"RequireAllTags":false,"RequireAllCategories":false,"NoCostOnly":false,"Systems":[],"WishlistOnly":false,"MinDaysOld":0}]
2024-11-02 20:01:05|ArchiSteamFarm-16344|INFO|enzomtp|Start() Démarrage...
2024-11-02 20:01:05|ArchiSteamFarm-16344|INFO|DiamaXV|OnConnected() Connecté à Steam !
2024-11-02 20:01:05|ArchiSteamFarm-16344|INFO|DiamaXV|OnConnected() Connexion en cours...
2024-11-02 20:01:05|ArchiSteamFarm-16344|INFO|DiamaXV|OnLoggedOn() 76561199208616037 connecté avec succès.
2024-11-02 20:01:05|ArchiSteamFarm-16344|INFO|DiamaXV|Init() Succès !
2024-11-02 20:01:06|ArchiSteamFarm-16344|ERROR|ASF|OnPICSChanges() System.InvalidOperationException: GlobalCache
   at FreePackages.PICSHandler.OnPICSChanges(UInt32 currentChangeNumber, IReadOnlyDictionary`2 appChanges, IReadOnlyDictionary`2 packageChanges)
   at FreePackages.FreePackages.OnPICSChanges(UInt32 currentChangeNumber, IReadOnlyDictionary`2 appChanges, IReadOnlyDictionary`2 packageChanges)
   at ArchiSteamFarm.Plugins.PluginsCore.<>c__DisplayClass31_0.<OnPICSChanges>b__0(ISteamPICSChanges plugin)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Threading.Tasks.Task.WhenAll(IEnumerable`1)
   at ArchiSteamFarm.Core.Utilities.InParallel(IEnumerable`1 tasks)
   at ArchiSteamFarm.Plugins.PluginsCore.OnPICSChanges(UInt32 currentChangeNumber, IReadOnlyDictionary`2 appChanges, IReadOnlyDictionary`2 packageChanges)
2024-11-02 20:01:06|ArchiSteamFarm-16344|INFO|DiamaXV|IsAnythingToFarm() Vérification de la première page des badges...
2024-11-02 20:01:07|ArchiSteamFarm-16344|INFO|DiamaXV|StartFarming() Nous n’avons rien à collecter sur ce compte !
2024-11-02 20:01:09|ArchiSteamFarm-16344|INFO|DiamaXV|ResetGamesPlayed() Traitement de la sélection GamesPlayedWhileIdle: 420530
2024-11-02 20:01:15|ArchiSteamFarm-16344|INFO|Draconix|Connect() Connexion...
2024-11-02 20:01:15|ArchiSteamFarm-16344|INFO|Draconix|OnConnected() Connecté à Steam !
2024-11-02 20:01:15|ArchiSteamFarm-16344|INFO|Draconix|OnConnected() Connexion en cours...
2024-11-02 20:01:15|ArchiSteamFarm-16344|INFO|Draconix|OnLoggedOn() 76561198403813730/JustAHA connecté avec succès.
2024-11-02 20:01:15|ArchiSteamFarm-16344|INFO|Draconix|Init() Succès !
2024-11-02 20:01:15|ArchiSteamFarm-16344|INFO|Draconix|IsAnythingToFarm() Vérification de la première page des badges...
2024-11-02 20:01:17|ArchiSteamFarm-16344|INFO|Draconix|StartFarming() Nous n’avons rien à collecter sur ce compte !
2024-11-02 20:01:19|ArchiSteamFarm-16344|INFO|Draconix|ResetGamesPlayed() Traitement de la sélection GamesPlayedWhileIdle: 440
2024-11-02 20:01:25|ArchiSteamFarm-16344|INFO|enzomtp|Connect() Connexion...
2024-11-02 20:01:25|ArchiSteamFarm-16344|INFO|enzomtp|OnConnected() Connecté à Steam !
2024-11-02 20:01:25|ArchiSteamFarm-16344|INFO|enzomtp|OnConnected() Connexion en cours...
2024-11-02 20:01:25|ArchiSteamFarm-16344|INFO|enzomtp|OnLoggedOn() 76561198149190660/enzomtp connecté avec succès.
2024-11-02 20:01:25|ArchiSteamFarm-16344|INFO|enzomtp|Init() Succès !
2024-11-02 20:01:25|ArchiSteamFarm-16344|INFO|enzomtp|IsAnythingToFarm() Vérification de la première page des badges...
2024-11-02 20:01:27|ArchiSteamFarm-16344|INFO|enzomtp|StartFarming() Nous n’avons rien à collecter sur ce compte !
2024-11-02 20:01:36|ArchiSteamFarm-16344|ERROR|ASF|Execute() An error occurred: MissingMethodException Attempted to access a missing method.
2024-11-02 20:02:05|ArchiSteamFarm-16344|DEBUG|DiamaXV|Refresh() Il n'y a aucune application qui nécessite une actualisation sur cette instance de bot.
2024-11-02 20:02:15|ArchiSteamFarm-16344|DEBUG|Draconix|Refresh() Il n'y a aucune application qui nécessite une actualisation sur cette instance de bot.
2024-11-02 20:02:25|ArchiSteamFarm-16344|DEBUG|enzomtp|Refresh() Il n'y a aucune application qui nécessite une actualisation sur cette instance de bot.
2024-11-02 20:03:38|ArchiSteamFarm-16344|INFO|enzomtp|CheckOccupationStatus() Ce compte est actuellement utilisé : ASF reprendra la collecte quand celui-ci sera libre...
2024-11-02 20:04:15|ArchiSteamFarm-16344|INFO|enzomtp|CheckOccupationStatus() Le compte n'est plus occupé : reprise du processus de collecte !
2024-11-02 20:06:06|ArchiSteamFarm-16344|ERROR|ASF|OnPICSChanges() System.InvalidOperationException: GlobalCache
   at FreePackages.PICSHandler.OnPICSChanges(UInt32 currentChangeNumber, IReadOnlyDictionary`2 appChanges, IReadOnlyDictionary`2 packageChanges)
   at FreePackages.FreePackages.OnPICSChanges(UInt32 currentChangeNumber, IReadOnlyDictionary`2 appChanges, IReadOnlyDictionary`2 packageChanges)
   at ArchiSteamFarm.Plugins.PluginsCore.<>c__DisplayClass31_0.<OnPICSChanges>b__0(ISteamPICSChanges plugin)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Threading.Tasks.Task.WhenAll(IEnumerable`1)
   at ArchiSteamFarm.Core.Utilities.InParallel(IEnumerable`1 tasks)
   at ArchiSteamFarm.Plugins.PluginsCore.OnPICSChanges(UInt32 currentChangeNumber, IReadOnlyDictionary`2 appChanges, IReadOnlyDictionary`2 packageChanges)
2024-11-02 20:11:06|ArchiSteamFarm-16344|ERROR|ASF|OnPICSChanges() System.InvalidOperationException: GlobalCache
   at FreePackages.PICSHandler.OnPICSChanges(UInt32 currentChangeNumber, IReadOnlyDictionary`2 appChanges, IReadOnlyDictionary`2 packageChanges)
   at FreePackages.FreePackages.OnPICSChanges(UInt32 currentChangeNumber, IReadOnlyDictionary`2 appChanges, IReadOnlyDictionary`2 packageChanges)
   at ArchiSteamFarm.Plugins.PluginsCore.<>c__DisplayClass31_0.<OnPICSChanges>b__0(ISteamPICSChanges plugin)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Threading.Tasks.Task.WhenAll(IEnumerable`1)
   at ArchiSteamFarm.Core.Utilities.InParallel(IEnumerable`1 tasks)
   at ArchiSteamFarm.Plugins.PluginsCore.OnPICSChanges(UInt32 currentChangeNumber, IReadOnlyDictionary`2 appChanges, IReadOnlyDictionary`2 packageChanges)
2024-11-02 20:16:04|ArchiSteamFarm-16344|FATAL|ASF|OnUnhandledException() System.ArgumentNullException: Value cannot be null. (Parameter 'FreePackages.GlobalCache')
   at System.ArgumentNullException.Throw(String)
   at System.ArgumentNullException.ThrowIfNull(Object , String )
   at FreePackages.ASFInfo.DoUpdate()
   at FreePackages.ASFInfo.<>c.<<-cctor>b__6_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
2024-11-02 20:16:04|ArchiSteamFarm-16344|ERROR|ASF|Exit() Erreur : Sortie avec un code d'erreur non nul 1!
2024-11-02 20:16:04|ArchiSteamFarm-16344|INFO|Microsoft.Hosting.Lifetime|Application is shutting down...
2024-11-02 20:16:04|ArchiSteamFarm-16344|INFO|DiamaXV|Stop() Arrêt...
2024-11-02 20:16:04|ArchiSteamFarm-16344|INFO|enzomtp|Stop() Arrêt...
2024-11-02 20:16:04|ArchiSteamFarm-16344|INFO|Draconix|Stop() Arrêt...
2024-11-02 20:16:04|ArchiSteamFarm-16344|INFO|enzomtp|OnDisconnected() Déconnecté de Steam !
2024-11-02 20:16:04|ArchiSteamFarm-16344|INFO|DiamaXV|OnDisconnected() Déconnecté de Steam !
2024-11-02 20:16:04|ArchiSteamFarm-16344|INFO|Draconix|OnDisconnected() Déconnecté de Steam !
```

**Comment by Citrinate** [comment]
This looks like the same error as #41.  You should be able to resolve it by deleting `FreePackages.cache` in the `asf/config` folder.

**Comment by enzomtpYT** [comment]
I read that issue before posting this one and already tried deleting this file.
It didn't fixed it, it keeps on making this error

**Comment by Citrinate** [comment]
I would expect the `System.Text.Json.JsonException` error and all errors involving `GlobalCache` to go away if that file is deleted (though maybe they'll come back the next time it's run).  Maybe you're deleting the wrong `FreePackages.cache` file?

The `LoadAssembliesFrom` errors at the start also indicate that ASF is having problems reading other files as well, and these errors are coming from ASF, not from the plugin.  I see ASF is complaining that you're trying to run in admin mode, so maybe there's an issue in how you're using ASF.  I can't really help with that.

I've made some changes which should improve reliability in cases like this.  It will still log errors, and those errors should be addressed if they show up every run, but it shouldn't crash anymore.  My assumption right now is that these errors are due to running ASF in an unusual way.  You can test this change using the latest build here: [FreePackages V1.5.2.3](https://github.com/Citrinate/FreePackages/actions/runs/11653070331/artifacts/2138181137)

**Comment by enzomtpYT** [comment]
Update: by now asf would've already crashed multiple times but it didn't, i checked the logs i don't even have any errors anymore, i would guess that new version fixed it? Thank you a lot for the help! I'll close the issue now!
