### ISSUE TITLE
ArchiSteamFarm V6.1.0.1 crashes

### ISSUE THREAD

**Issue by kotenok2000** [Citrinate/FreePackages#67]
[ArchiSteamFarm V6.1.0.1](https://github.com/JustArchiNET/ArchiSteamFarm/releases/tag/6.1.0.1) crashes when using FreePackages 1.5.2.3
```
2024-11-19 03:33:18|ArchiSteamFarm-17188|INFO|ASF|InitCore() ArchiSteamFarm V6.1.0.1 (win-x64/5ca44dbc6d79417c85d759ab3623447b | .NET 9.0.0; win-x64; Microsoft Windows 10.0.26100) in [E:\Steam\ArchiSteamFarm]
2024-11-19 03:33:18|ArchiSteamFarm-17188|INFO|ASF|InitCore() Copyright © 2015-2024 JustArchiNET
2024-11-19 03:33:30|ArchiSteamFarm-17188|INFO|ASF|InitPlugins() Инициализация Plugins...
2024-11-19 03:33:31|ArchiSteamFarm-17188|ERROR|ASF|InitPlugins() System.Reflection.CustomAttributeFormatException: 'Name' property specified was not found.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1&, RuntimeModule, Int32, RuntimeType, Boolean, ListBuilder`1)
   --- End of inner exception stack trace ---
   at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1&, RuntimeModule, Int32, RuntimeType, Boolean, ListBuilder`1)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule, Int32, Int32, RuntimeType)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType, RuntimeType, Boolean)
   at System.RuntimeType.GetCustomAttributes(Type, Boolean)
   at System.Attribute.GetCustomAttributes(MemberInfo, Type, Boolean)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttributes(MemberInfo, Type, Boolean)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttributes[T](MemberInfo, Boolean)
   at System.Composition.Convention.ConventionBuilder.GetCustomAttributes(Type reflectedType, MemberInfo member)
   at System.Composition.Convention.AttributedModelProviderExtensions.GetDeclaredAttribute[TAttribute](AttributedModelProvider convention, Type reflectedType, MemberInfo member)
   at System.Composition.TypedParts.Discovery.TypeInspector.InspectTypeForPart(TypeInfo type, DiscoveredPart& part)
   at System.Composition.TypedParts.TypedPartExportDescriptorProvider..ctor(IEnumerable`1 types, AttributedModelProvider attributeContext)
   at System.Composition.Hosting.ContainerConfiguration.CreateContainer()
   at ArchiSteamFarm.Plugins.PluginsCore.InitPlugins()
2024-11-19 03:33:41|ArchiSteamFarm-17188|ERROR|ASF|Exit() Завершено с кодом ошибки 1!
```

**Comment by Qwest8K** [comment]
Same:
```
2024-11-19 08:15:57|ArchiSteamFarm-16972|INFO|ASF|InitCore() ArchiSteamFarm V6.1.0.1 (win-x64/5ca44dbc6d79417c85d759ab3623447b | .NET 9.0.0; win-x64; Microsoft Windows 10.0.19045) in [D:\PPROGRAMS\ASF]
2024-11-19 08:15:57|ArchiSteamFarm-16972|INFO|ASF|InitCore() Copyright © 2015-2024 JustArchiNET
2024-11-19 08:15:58|ArchiSteamFarm-16972|INFO|ASF|InitPlugins() Инициализация Plugins...
2024-11-19 08:15:58|ArchiSteamFarm-16972|ERROR|ASF|InitPlugins() System.Reflection.CustomAttributeFormatException: 'Name' property specified was not found.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1&, RuntimeModule, Int32, RuntimeType, Boolean, ListBuilder`1)
   --- End of inner exception stack trace ---
   at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1&, RuntimeModule, Int32, RuntimeType, Boolean, ListBuilder`1)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule, Int32, Int32, RuntimeType)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType, RuntimeType, Boolean)
   at System.RuntimeType.GetCustomAttributes(Type, Boolean)
   at System.Attribute.GetCustomAttributes(MemberInfo, Type, Boolean)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttributes(MemberInfo, Type, Boolean)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttributes[T](MemberInfo, Boolean)
   at System.Composition.Convention.ConventionBuilder.GetCustomAttributes(Type reflectedType, MemberInfo member)
   at System.Composition.Convention.AttributedModelProviderExtensions.GetDeclaredAttribute[TAttribute](AttributedModelProvider convention, Type reflectedType, MemberInfo member)
   at System.Composition.TypedParts.Discovery.TypeInspector.InspectTypeForPart(TypeInfo type, DiscoveredPart& part)
   at System.Composition.TypedParts.TypedPartExportDescriptorProvider..ctor(IEnumerable`1 types, AttributedModelProvider attributeContext)
   at System.Composition.Hosting.ContainerConfiguration.CreateContainer()
   at ArchiSteamFarm.Plugins.PluginsCore.InitPlugins()
2024-11-19 08:16:08|ArchiSteamFarm-16972|ERROR|ASF|Exit() Завершено с кодом ошибки 1!
```

**Comment by Citrinate** [comment]
This issue only effects non-generic variants of ASF.

I've fixed this crash, but I've only tested on non-generic ASF just enough to ensure it doesn't crash on startup.  If you'd like to test the latest build you can get it here: https://github.com/Citrinate/FreePackages/actions/runs/11965520506/artifacts/2222306207

**Comment by Qwest8K** [comment]
Thanks. ASF is working again.
